extend type Mutation{
  verifyAndAttachVtexSecrets(input: VerifyAndAttachVtexSecretsInput!): Boolean! @hasOrganizationRole(role: ["ADMIN"]) @isVerified @isAuthenticated
}

input VerifyAndAttachVtexSecretsInput{
  xVtexApiAppKey: String!
  xVtexApiAppToken: String!
  accountName: String!
  organizationId: String!
}

extend type Organization{
  vtexIntegration: Boolean!
}