---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: plugone-redirect
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: go-staging.plugone.io
    http:
      paths:
      - backend:
          serviceName: plugone-redirect-staging
          servicePort: 80
