---
apiVersion: v1
kind: Secret
metadata:
  name: plugone-api-secret
type: Opaque
data:
  CREATE_ORGANIZATION_WITHOUT_INTEGRATION_SECRET: OXNhdmtGJUEpPFdBZEUzIw==
  DB_USER: cGx1Z29uZV9hcHBfdXNlcg==
  DB_PASSWORD: Mjgxd1F6d0pzSWhqSmREOA==
  DB_DATABASE: cGx1Z29uZS11c2Vycy1zdGFnaW5n
  DB_PORT: NTQzMg==
  DB_HOST: cGx1Z29uZS1zdGFnaW5nLWRiLmNubDNhcGtxb28xZS51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=
  DIGITAL_OCEAN_AWS_ACCESS_KEY_ID: SVE2N09IUExaTUVURktMWU5WUjc=
  DIGITAL_OCEAN_AWS_SECRET_ACCESS_KEY: dkNKMlRjRE9McjV2d0tBdFV1Q1BBWDRSR1lCc3N3UjJaNkcxS21Yd2w3UQ==
  DIGITAL_OCEAN_SPACES_END_POINT: bnljMy5kaWdpdGFsb2NlYW5zcGFjZXMuY29t
  ENTERPRISE_TOKEN: Jl9VbVg/UCEhTGs5
  JWT_SECRET: YSY0TCkteFNMRFE1eEB2bQ==
  LOJA_INTEGRADA_APPLICATION_KEY: ZDBkMjg4OGItYTYyNS00YWU3LTk4YTQtM2FlYWNjNWEwZTcx
  MAIL_PASS: YjgwYzlhY2YxYWZiODI0ZGU0YmViNDRjNTFjMzk0NzgtZjdkMGIxMDctZThkMzY2NDY=
  MONGO_URI: bW9uZ29kYitzcnY6Ly9kYl9wbHVnb25lX3VzZXI6ZzAzeEY3Qm4zU3NseXVuVUBjbHVzdGVyc3RhZ2UtanpyYWouYXp1cmUubW9uZ29kYi5uZXQvcGx1Z29uZT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  ORDERS_SERVICE_PASSWORD: dmFkZ25xQSkvciNVTCw0bg==
  REDIS_CACHEKEY: U0YyMnNMVENpRk5NNmkzVzFCTEcxK1pWVXdXOEhXUnYrb3daM010U0RTST0=
