extend type Query {
  getPendingMembersByOrganizationId: [UserOrganization]! @hasOrganizationRole(role: ["ADMIN"]) @organizationPaidVerify @enterpriseFeature @isVerified @acceptTermsAndConditions @isAuthenticated
}

extend type Mutation {
  handleMemberInvitation(input: HandleMemberInvitationInput!): UserOrganization!
    @hasOrganizationRole(role: ["ADMIN"])
    @organizationPaidVerify
    @isVerified
    @enterpriseFeature
    @acceptTermsAndConditions
    @isAuthenticated
  deleteMemberInvitation(input: DeleteMemberInvitationInput!): Boolean!
    @hasOrganizationRole(role: ["ADMIN"])
    @organizationPaidVerify
    @isVerified
    @acceptTermsAndConditions
    @isAuthenticated
}

input DeleteMemberInvitationInput {
  affiliateId: String!
}

input HandleMemberInvitationInput {
  userOrganizationId: String!
  inviteStatus: ResponseInviteStatus!
}

enum ResponseInviteStatus {
  refused
  accept
}

type UserOrganization {
  id: String!
  inviteStatus: OrganizationInviteStatus!
  inviteHash: String
  updatedAt: Datetime!
  createdAt: Datetime!
  organization: Organization!
  user: User!
  active: Boolean!
  organizationRole: OrganizationRole!
  isRequested: Boolean
}
