apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-plugone-api-staging
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: gabriel.tamura@b8one.com
    privateKeySecretRef:
      name: letsencrypt-plugone-api-staging
    solvers:
      - http01:
          ingress:
            class: nginx