extend type Mutation {
  sendOrganizationComissionOrder(input: SendOrganizationComissionOrderInput!): Boolean! @hasOrganizationRole(role: ["ADMIN"]) @organizationPaidVerify @isVerified @isAuthenticated
}

extend type Query {
  getOrganizationComissionOrder: [ComissionsOrder]! @hasOrganizationRole(role: ["ADMIN"]) @isVerified @isAuthenticated
}

type ComissionsOrder {
  type: String!
  order: Number!
}

input SendOrganizationComissionOrderInput {
  comissions: [ComissionsOrder]!
}
