# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- staging

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: DockerBuild
      inputs:
        command: 'build'
        Dockerfile: '**/Dockerfile'
        arguments: |
          --secret 
          dbuser=$(DB_USER)
          dbpassword=$(DB_PASSWORD)
          dbdatabase=$(DB_DATABASE)
          dbport=$(DB_PORT)
          dbhost=$(DB_HOST)
        tags: |
          $(Build.BuildId)
          latest

    - task: Docker@2
      displayName: DockerPush
      inputs:
        containerRegistry: 'gabrieltamura-dockerhub'
        repository: 'gabrieltamurab8one/plugone-api-staging'
        command: 'push'
        tags: |
          $(Build.BuildId)
          latest