pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  branches:
      include:
      - staging

resources:
  containers:
  - container: postgres
    image: 'postgres:11.3-alpine'
    ports:
    - 5432:5432/tcp
    env:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

jobs:
- job: Tests
  pool:
    vmImage: 'ubuntu-16.04'
  services: 
    postgres: postgres
  steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Use Node.js 12'

    - script: |
        npm install
        npm run test
      env: 
        DB_TEST_USER: postgres
        DB_TEST_PASSWORD: postgres
        DB_TEST_DATABASE: postgres
        DB_TEST_HOST: localhost
        DB_TEST_PORT: 5432
