resources:
  containers:
  - container: linux container
    image: ubuntu:16.04
  - container: pg11
    image: postgres:11

pool:
  vmImage: 'ubuntu-16.04'

container: linux container

steps:
  build:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: appia-api
          POSTGRES_DB: appia-api
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      NODE_ENV: test
      PG_PORT: 5432
      DB_TEST_USER: appia-api
      SUIT: appia-api
      DB_TEST_DATABASE: appia-api
    steps:

      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
        env:
          SOMEVAR: '$(TestVar)'
          DB_TEST_USER: postgres
          # DB_TEST_PASSWORD:
          DB_TEST_DATABASE: testeplugone
          DB_TEST_HOST: postgres
          DB_TEST_PORT: 5432

      - script: |
          npm install
          npm run test
        displayName: 'npm install and output coverage'