pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  branches:
    include:
    - releases/*
    exclude:
    - feature/*
    - staging
    - master

resources:
  containers:
  - container: postgres_integration_integration_tests
    image: postgres:10.8
    ports:
    - 5432:5432/tcp
    env:
      POSTGRES_USER: plugone-api
      POSTGRES_DB: plugone-api
    options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  - container: redis_integration_integration_tests
    image: redis:latest
    ports:
    - 6379:6379/tcp
    env:
      REDIS_HOST: "127.0.0.1"
      REDIS_PORT: 6379

jobs:
- job: Tests
  services: 
    postgres: postgres_integration_integration_tests
    redis: redis_integration_integration_tests
  pool:
    vmImage: 'ubuntu-16.04'
  variables: 
    NODE_ENV: test
    DB_TEST_USER: plugone-api
    DB_TEST_DATABASE: plugone-api
    DB_TEST_PORT: 5432
    REDIS_HOST: "127.0.0.1"
    REDIS_PORT: 6379
    MAIL_HOST: smtp.mailtrap.io
    MAIL_PORT: 2525
    MAIL_USER: cd47bbf212775c
    MAIL_PASS: dce5f9d71d1971
    JWT_SECRET: testing
    DIGITAL_OCEAN_AWS_ACCESS_KEY_ID: IQ67OHPLZMETFKLYNVR7
    DIGITAL_OCEAN_AWS_SECRET_ACCESS_KEY: vCJ2TcDOLr5vwKAtUuCPAX4RGYBsswR2Z6G1KmXwl7Q
    DIGITAL_OCEAN_SPACES_END_POINT: nyc3.digitaloceanspaces.com
    BUCKET_NAME: plugone-staging
    PORT: 80
  steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Use Node.js 12'

    - script: |
        npm install
        npm run knex:migrate:latest --env test
        npm run test
