resources:
  containers:
  - container: 'postgres_linux_container_for_integration_tests'
    image: 'postgres:11.3-alpine'
    ports:
    - 9999:5432/tcp
    env:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

jobs:
- template: 'teste template'
  parameters:
    job:
      name: 'linux'
      displayName: 'Build on Linux'
    pool:
      vmImage: 'ubuntu-16.04'
    services:
      postgres:
        containerName: 'postgres_linux_container_for_integration_tests'
        databaseConnectionString: >-
          Host=localhost;
          Port=9999;
          Database=plugonetests;
          Username=$(IntegrationTests.Database.Todo.Username);
          Password=$(IntegrationTests.Database.Todo.Password);