pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  branches:
      include:
      - staging

# resources:
#   containers:
#   - container: 'postgres_linux_container_for_integration_tests'
#     image: 'postgres:11.3-alpine'
#     ports:
#     - 5432:5432/tcp
#     env:
#       POSTGRES_DB: postgres
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres

jobs:
- job: Tests
  pool:
    vmImage: 'ubuntu-16.04'
  # services:
  #   postgres:
  #     containerName: 'postgres_linux_container_for_integration_tests'
  #     databaseConnectionString: >-
  #       Host=localhost;
  #       Port=5432;
  #       Database=plugonetests;
  #       Username=$(IntegrationTests.Database.Todo.Username);
  #       Password=$(IntegrationTests.Database.Todo.Password);
  steps:
    # Ensure Node.js 12 is active
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Use Node.js 12'

    # Ensure Python 2.7 is active
    - script: |
        npm run install
        npm run test