trigger:
- staging

resources:
  containers:
  - container: pg11
    image: postgres:11
    ports:
        - 5432

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Test
  displayName: Test Suit
  jobs:  
  - job: Test
    displayName: Test
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - script: |
        apt install -y postgresql-client
        psql --host=postgres --username=postgres --command="SELECT 1;"

    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
      env:
        SOMEVAR: '$(TestVar)'
        DB_TEST_USER: postgres
        # DB_TEST_PASSWORD:
        DB_TEST_DATABASE: testeplugone
        DB_TEST_HOST: postgres
        DB_TEST_PORT: 5432

    - script: |
        npm install
        npm run test
      displayName: 'npm install and output coverage'