pool:
  vmImage: 'Ubuntu 16.04'

pr:
  branches:
    include:
    - feature/*
    - master

resources:
  containers:
  - container: postgres_integration_tests
    image: postgres:10.8
    ports:
    - 5432:5432/tcp
    env:
      POSTGRES_USER: plugone-api
      POSTGRES_DB: plugone-api
    options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

jobs:
- job: Tests
  services: 
    postgres: postgres_integration_tests
  pool:
    vmImage: 'ubuntu-16.04'
  variables: 
    NODE_ENV: test
    DB_TEST_USER: plugone-api
    DB_TEST_DATABASE: plugone-api
    DB_TEST_PORT: 5432
    MAIL_HOST: smtp.mailtrap.io
    MAIL_PORT: 2525
    MAIL_USER: cd47bbf212775c
    MAIL_PASS: dce5f9d71d1971
    JWT_SECRET: testing
    PORT: 5000
  steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Use Node.js 12'

    - script: |
        npm install
        npm run knex:migrate:latest --env test
        npm run test
