# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- staging

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: DockerBuild
      inputs:
        command: build
        containerRegistry: 'gabrieltamura-dockerhub'
        repository: 'gabrieltamurab8one/plugone-api-staging'
        Dockerfile: '**/Dockerfile'
        includeLatestTag: true
        tags: $(Build.BuildId)' 
        arguments: '--build-arg dbuser=$(DB_USER) --build-arg dbpassword=$(DB_PASSWORD) --build-arg dbdatabase=$(DB_DATABASE) --build-arg dbport=$(DB_PORT) --build-arg dbhost=$(DB_HOST)'

    - task: Docker@2
      displayName: DockerPush
      inputs:
        command: push
        containerRegistry: 'gabrieltamura-dockerhub'
        repository: 'gabrieltamurab8one/plugone-api-staging'
        tags: $(Build.BuildId)' 