extend type Query{
    listAvailableServices(input: ListAvailableServicesInput!): [Services]! @hasOrganizationRole(role: ["ADMIN"]) @isVerified @isAuthenticated 
}

input ListAvailableServicesInput {
    organizationId: String!
}

type Services{
    id: String!
    name: String!
    active: Boolean!
    updatedAt: Datetime!
    createdAt: Datetime!
    hasOrganization: Boolean!
}

extend type Mutation{
    createServiceInOrganization(input: CreateServiceInOrganizationInput!): Boolean! @hasOrganizationRole(role: ["ADMIN"]) @isVerified @isAuthenticated 
}

input CreateServiceInOrganizationInput{
    serviceId: String!
    organizationId: String!
}