extend type Mutation{
    createServiceInOrganization(input: CreateServiceInOrganizationInput!): Boolean! @hasOrganizationRole(role: ["ADMIN"]) @isVerified @isAuthenticated 
}

input CreateServiceInOrganizationInput{
    serviceId: String!
    organizationId: String!
}