extend type Query {
  getOriginalUrlByCode(input: GetOriginalUrlByCodeInput!): String!
  getLatestUrl: [ShortenerUrl]! @organizationPaidVerify @isVerified @acceptTermsAndConditions @isAuthenticated
}

input GetOriginalUrlByCodeInput {
  urlCode: String!
}

type ShortenerUrl {
  id: String!
  originalUrl: String!
  shortUrl: String!
  urlCode: String!
  createdAt: Datetime!
  updatedAt: Datetime!
}