extend type Query {
  getOriginalUrlByCode(input: GetOriginalUrlByCodeInput!): String!
  getLatestUrl: [GetLatestUrl] @organizationPaidVerify @isVerified @acceptTermsAndConditions @isAuthenticated
}

input GetOriginalUrlByCodeInput {
  urlCode: String!
}

type ShortenerUrl {
  id: String!
  originalUrl: String!
  shortUrl: String!
  urlCode: String!
  createdAt: Datetime!
  updatedAt: Datetime!
}

type GetLatestUrl {
  user_id: String
  organization_id: String
  id_url_shorten: String
  original_url: String
  short_url: String
  created_at: String
}