extend type Mutation {
  installAffiliateStoreApp(input: InstallAffiliateStoreAppInput!): Boolean! @hasOrganizationRole(role: ["ADMIN"]) @organizationPaidVerify @isVerified @acceptTermsAndConditions @isAuthenticated
  uninstallAffiliateStoreApp(input: UninstallAffiliateStoreAppInput!): Boolean! @hasOrganizationRole(role: ["ADMIN"]) @organizationPaidVerify @isVerified @acceptTermsAndConditions @isAuthenticated
  editOrganizationAffiliateStoreAppConfig(input: EditOrganizationAffiliateStoreAppConfigInput!): Boolean!
    @hasOrganizationRole(role: ["ADMIN"])
    @organizationPaidVerify
    @isVerified
    @acceptTermsAndConditions
    @isAuthenticated
}

extend type Query {
  getAffiliateStoreApps: [AffiliateStoreApp]! @organizationPaidVerify @enterpriseOrNeptuneFeature @hasOrganizationRole(role: ["ADMIN"]) @isVerified @acceptTermsAndConditions @isAuthenticated
  getAffiliateStoreApp(input: GetAffiliateStoreAppInput!): AffiliateStoreApp @hasOrganizationRole(role: ["ADMIN"]) @isVerified @acceptTermsAndConditions @isAuthenticated
  getInstalledAffiliateStoreApps: [OrganizationAffiliateStoreApp]! @hasOrganizationRole(role: ["ADMIN"]) @isVerified @acceptTermsAndConditions @isAuthenticated
  getInstalledAffiliateStoreApp(input: GetInstalledAffiliateStoreAppInput!): OrganizationAffiliateStoreApp
    @hasOrganizationRole(role: ["ADMIN", "MEMBER"])
    @isVerified
    @acceptTermsAndConditions
    @isAuthenticated
}

type AffiliateStoreApp {
  id: String!
  name: String!
  displayName: String!
  shortDescription: String!
  description: String!
  tags: [String]!
  mainImage: String!
  images: [String]
  authorName: String!
  authorLogo: String
  authorUrl: String
  configs: [AffiliateStoreAppConfig]!
  isInstalled: Boolean!
  plans: [String]!
}

type AffiliateStoreAppConfig {
  name: String!
  displayName: String!
  exampleValue: String
  type: String
  required: Boolean
}

type OrganizationAffiliateStoreApp {
  id: String!
  affiliateStoreApp: AffiliateStoreApp
  configs: [OrganizationAffiliateStoreAppConfig]!
  requirements: [OrganizationAffiliateStoreAppRequirements]!
  active: Boolean!
}

type OrganizationAffiliateStoreAppConfig {
  key: String!
  value: String!
}

type OrganizationAffiliateStoreAppRequirements {
  id: String!
  value: String!
  required: Boolean
  active: Boolean
  additionalFields: String
}

input GetAffiliateStoreAppInput {
  id: String!
}

input GetInstalledAffiliateStoreAppInput {
  id: String!
}

input InstallAffiliateStoreAppInput {
  id: String!
  configs: [AffiliateStoreAppConfigInput]!
  requirements: [AffiliateStoreAppRequirementInput]!
}

input UninstallAffiliateStoreAppInput {
  id: String!
}

input EditOrganizationAffiliateStoreAppConfigInput {
  id: String!
  configs: [AffiliateStoreAppConfigInput]!
  requirements: [AffiliateStoreAppRequirementInput]!
}

input AffiliateStoreAppConfigInput {
  key: String!
  value: String!
}

input AffiliateStoreAppRequirementInput {
  id: String!
  value: String!
  required: Boolean
  active: Boolean
  additionalFields: String
}
