extend type Mutation {
  createIntegration(input: CreateIntegrationInput!): Boolean @hasOrganizationRole(role: ["ADMIN"]) @organizationPaidVerify @acceptTermsAndConditions @isVerified @isAuthenticated
  createIuguIntegration(input: CreateIuguIntegrationInput!): Boolean @hasOrganizationRole(role: ["ADMIN"]) @organizationPaidVerify @acceptTermsAndConditions @isVerified @isAuthenticated
}

input CreateIntegrationInput {
  secrets: IntegrationSecrets!
  type: Integrations!
}

input CreateIuguIntegrationInput {
  secrets: IuguSecret!
}

input IuguSecret {
  appKey: String!
}

enum Integrations {
  vtex
  loja_integrada
  iugu
  klipfolio
}

input IntegrationSecrets {
  xVtexApiAppKey: String
  xVtexApiAppToken: String
  accountName: String
  appKey: String
}

extend type Organization {
  integration: Integration
}

type Integration {
  type: Integrations!
  status: Boolean!
  asSaas: Boolean!
  createdAt: Datetime!
  updatedAt: Datetime!
}
