extend type Mutation {
  createIntegration(input: CreateIntegrationInput!): Boolean
    @hasOrganizationRole(role: ["ADMIN"])
    @organizationPaidVerify
    @isVerified
    @isAuthenticated
}

input CreateIntegrationInput {
  secrets: IntegrationSecrets!
  type: Integrations!
}

enum Integrations {
  vtex
  loja_integrada
}

input IntegrationSecrets {
  xVtexApiAppKey: String
  xVtexApiAppToken: String
  accountName: String
  appKey: String
}

extend type Organization {
  integration: Integration
}

type Integration {
  type: Integrations!
  status: Boolean!
  createdAt: Datetime!
  updatedAt: Datetime!
}
