extend type Mutation {
  createIntegration(input: CreateIntegrationInput!): Boolean
    @hasOrganizationRole(role: ["ADMIN"])
    @organizationPaidVerify
    @isVerified
    @isAuthenticated
}

input CreateIntegrationInput {
  secrets: IntegrationSecrets!
  type: Integrations!
}

enum Integrations {
  vtex
}

input IntegrationSecrets {
  xVtexApiAppKey: String!
  xVtexApiAppToken: String!
  accountName: String!
}

extend type Organization {
  integration: Integration
}

type Integration {
  status: Boolean!
  createdAt: Datetime!
  updatedAt: Datetime!
}
