extend type Mutation {
  sendOrganizationCommissionOrder(input: SendOrganizationCommissionOrderInput!): Boolean! @hasOrganizationRole(role: ["ADMIN"]) @organizationPaidVerify @isVerified @isAuthenticated
}

extend type Query {
  getOrganizationCommissionOrder: [CommissionsOrder]! @hasOrganizationRole(role: ["ADMIN"]) @isVerified @isAuthenticated
}

type CommissionsOrder {
  type: String!
  order: Int!
  id: Int!
}

input SendOrganizationCommissionOrderInput {
  commissions: [CommissionOrderInput]!
}

input CommissionOrderInput {
  type: String!
  order: Int!
}
