extend type Mutation {
  handleOrganizationFinantialConciliationConfiguration(input: handleOrganizationFinantialConciliationConfigurationInput!): Boolean!
    @hasOrganizationRole(role: ["ADMIN"])
    @isVerified
    @acceptTermsAndConditions
    @organizationPaidVerify
    @isAuthenticated
  handleOrganizationFinantialConciliationStatusAdvance(input: handleOrganizationFinantialConciliationStatusAdvanceInput!): String!
    @hasOrganizationRole(role: ["ADMIN"])
    @isVerified
    @acceptTermsAndConditions
    @organizationPaidVerify
    @isAuthenticated
}

extend type Query {
  getOrganizationFinantialConciliation: getOrganizationFinantialConciliationQuery! @hasOrganizationRole(role: ["ADMIN"]) @isVerified @acceptTermsAndConditions @isAuthenticated
  getAffiliatesValuesByMonth(input: getAffiliatesValuesByMonthInput!): getAffiliatesValuesByMonthQuery! @hasOrganizationRole(role: ["ADMIN"]) @isVerified @acceptTermsAndConditions @isAuthenticated
  getDailyRevenueAndCommissions(input: getDailyRevenueAndCommissionsInput!): getDailyRevenueAndCommissionsQuery!
    @hasOrganizationRole(role: ["ADMIN"])
    @isVerified
    @acceptTermsAndConditions
    @isAuthenticated
  getOrderListByAffiliateIdAndReferenceMonth(input: getOrderListByAffiliateIdAndReferenceMonthInput!): getOrderListByAffiliateIdAndReferenceMonthQuery!
    @hasOrganizationRole(role: ["ADMIN"])
    @isVerified
    @acceptTermsAndConditions
    @isAuthenticated
  downloadFinantialConciliationCSVByReferenceMonth(input: downloadFinantialConciliationCSVByReferenceMonthInput!): String!
    @hasOrganizationRole(role: ["ADMIN"])
    @isVerified
    @acceptTermsAndConditions
    @isAuthenticated
}

type getOrganizationFinantialConciliationQuery {
  close_day: Int
  payment_day: Int
  automatic_closure: Boolean
  createdAt: Datetime
  updatedAt: Datetime
}

input handleOrganizationFinantialConciliationConfigurationInput {
  close_day: Int
  payment_day: Int
  automatic_closure: Boolean
}

input handleOrganizationFinantialConciliationStatusAdvanceInput {
  referenceMonth: String!
}

type getAffiliatesValuesByMonthQuery {
  affiliates: [AffiliateValues]!
}

type InvoiceData {
  id:  String
  url: String
  received: Boolean
}

type AffiliateValues {
  affiliateId: String!
  revenue: Float!
  commission: Float!
  name: String
  document: String
  agency: String
  account: String
  bank: String
  orders: Int
  plugFormFields: String
  invoice: InvoiceData
}

input getAffiliatesValuesByMonthInput {
  year_month: String!
}

type getDailyRevenueAndCommissionsQuery {
  status: String!
  days: [DailyRevenueAndCommission]
  orders: Int!
}

type DailyRevenueAndCommission {
  day: String!
  revenue: Float!
  commission: Float!
}

input getDailyRevenueAndCommissionsInput {
  year_month: String!
}

input getOrderListByAffiliateIdAndReferenceMonthInput {
  affiliateId: String!
  referenceMonth: String!
}

type getOrderListByAffiliateIdAndReferenceMonthQuery {
  id: String! #affiliateId
  name: String!
  document: String!
  orders: Int!
  revenue: Float!
  commission: Float!
  orderList: [OrderList]!
}

type OrderList {
  id: String!
  client: String!
  date: String!
  value: Float!
  commission: Float!
  isPaid: Boolean!
}

input downloadFinantialConciliationCSVByReferenceMonthInput {
  referenceMonth: String!
}
