extend type Mutation {
  handleOrganizationFinantialConciliationConfiguration(input: handleOrganizationFinantialConciliationConfigurationInput!): Boolean!
    @hasOrganizationRole(role: ["ADMIN"])
    @acceptTermsAndConditions
    @organizationPaidVerify
    @isVerified
    @isAuthenticated
}

extend type Query {
  getOrganizationFinantialConciliation: getOrganizationFinantialConciliationQuery! @hasOrganizationRole(role: ["ADMIN"]) @acceptTermsAndConditions @isVerified @isAuthenticated
}

type getOrganizationFinantialConciliationQuery {
  close_day: Int
  payment_day: Int
  automatic_closure: Boolean
  createdAt: Datetime
  updatedAt: Datetime
}

input handleOrganizationFinantialConciliationConfigurationInput {
  close_day: Int
  payment_day: Int
  automatic_closure: Boolean
}
