extend type Mutation {
  handleAffiliateStore(input: HandleAffiliateStoreInput!): AffiliateStore!
    @hasServiceRole(role: ["ANALYST"], serviceName: "affiliate")
    @organizationPaidVerify
    @vtexFeature
    @isVerified
    @isAuthenticated
  addProductOnAffiliateStore(input: AddProductOnAffiliateStoreInput!): AffiliateStoreProduct!
    @hasServiceRole(role: ["ANALYST"], serviceName: "affiliate")
    @organizationPaidVerify
    @vtexFeature
    @isVerified
    @isAuthenticated
  handleProductOnAffiliateStoreActivity(input: HandleProductOnAffiliateStoreActivityInput!): AffiliateStoreProduct!
    @hasServiceRole(role: ["ANALYST"], serviceName: "affiliate")
    @organizationPaidVerify
    @vtexFeature
    @isVerified
    @isAuthenticated
  handleProductOnAffiliateStoreOrder(input: [HandleProductOnAffiliateStoreOrderInput]!): Boolean!
    @hasServiceRole(role: ["ANALYST"], serviceName: "affiliate")
    @organizationPaidVerify
    @vtexFeature
    @isVerified
    @isAuthenticated
  handleProductOnAffiliateStoreSearchable(input: HandleProductOnAffiliateStoreSearchableInput!): AffiliateStoreProduct!
    @hasServiceRole(role: ["ANALYST"], serviceName: "affiliate")
    @organizationPaidVerify
    @vtexFeature
    @isVerified
    @isAuthenticated
}

extend type Query {
  getAffiliateStore: AffiliateStore @hasServiceRole(role: ["ANALYST"], serviceName: "affiliate") @isVerified @isAuthenticated
  getAffiliateStoreProducts(input: GetAffiliateStoreProductsInput): [AffiliateStoreProductFormatted]!
    @hasServiceRole(role: ["ANALYST"], serviceName: "affiliate")
    @vtexFeature
    @isVerified
    @isAuthenticated
  getAffiliateStoreAddedProducts: [AffiliateStoreProduct]! @hasServiceRole(role: ["ANALYST"], serviceName: "affiliate") @vtexFeature @isVerified @isAuthenticated
}

input HandleProductOnAffiliateStoreSearchableInput {
  affiliateStoreProductId: String!
  searchable: Boolean!
}

input HandleProductOnAffiliateStoreOrderInput {
  affiliateStoreProductId: String!
  order: Int!
}

input HandleProductOnAffiliateStoreActivityInput {
  affiliateStoreProductId: String!
  activity: Boolean!
}

input AddProductOnAffiliateStoreInput {
  productId: String!
}

input GetAffiliateStoreProductsInput {
  term: String!
}

type AffiliateStoreProductFormatted {
  productId: String!
  price: String!
  image: String!
}

input HandleAffiliateStoreInput {
  avatar: AffiliateAvatarInput
  cover: AffiliateCoverInput
  name: String
  description: String
  facebook: String
  youtube: String
  twitter: String
  tiktok: String
  instagram: String
}

input AffiliateAvatarInput {
  mimetype: String
  data: Upload!
}

input AffiliateCoverInput {
  mimetype: String
  data: Upload!
}

type AffiliateStore {
  id: String!
  usersOrganizationServiceRoles: UserOrganizationService!
  avatar: String
  cover: String
  name: String
  description: String
  facebook: String
  youtube: String
  twitter: String
  tiktok: String
  instagram: String
  createdAt: Datetime!
  updatedAt: Datetime!
}

type AffiliateStoreProduct {
  id: String!
  affiliateStoreId: String!
  productId: String!
  active: Boolean!
  searchable: Boolean!
  order: Int!
}
