extend type Mutation {
  handleAffiliateStore(input: HandleAffiliateStoreInput!): AffiliateStore! @hasServiceRole(role: ["ANALYST"], serviceName: "affiliate") @organizationPaidVerify @isVerified @isAuthenticated
}

extend type Query {
  getAffiliateStore: AffiliateStore! @hasServiceRole(role: ["ANALYST"], serviceName: "affiliate") @isVerified @isAuthenticated
  getAffiliateStoreProducts(input: GetAffiliateStoreProductsInput): [AffiliateStoreProduct]! @hasServiceRole(role: ["ANALYST"], serviceName: "affiliate") @vtexFeature @isVerified @isAuthenticated
}

input GetAffiliateStoreProductsInput {
  term: String!
}

type AffiliateStoreProduct {
  productId: String!
  price: String!
  image: String!
}

input HandleAffiliateStoreInput {
  avatar: AffiliateAvatarInput
  cover: AffiliateCoverInput
  name: String
  description: String
  facebook: String
  youtube: String
  twitter: String
  tiktok: String
  instagram: String
}

input AffiliateAvatarInput {
  mimetype: String
  data: Upload!
}

input AffiliateCoverInput {
  mimetype: String
  data: Upload!
}

type AffiliateStore {
  id: String!
  usersOrganizationServiceRoles: UserOrganizationService!
  avatar: String!
  cover: String!
  name: String!
  description: String!
  facebook: String!
  youtube: String!
  twitter: String!
  tiktok: String!
  instagram: String!
  createdAt: Datetime!
  updatedAt: Datetime!
}
