extend type Query {
  userOrganizationPermissions(input: UserOrganizationPermissionsInput): [OrganizationPermissions]!
    @hasOrganizationRole(role: ["ADMIN", "MEMBER"])
    @isVerified
    @acceptTermsAndConditions
    @isAuthenticated
}

input UserOrganizationPermissionsInput {
  name: PermissionName!
}

type OrganizationPermissions {
  id: String!
  permissionName: PermissionName!
  organizationRoleName: OrganizationRoleName!
  grant: PermissionGrant!
}

enum PermissionName {
  settings
  members
  integrations
  affiliate
}

enum PermissionGrant {
  write
  read
  hide
}
