extend type Query {
  getAllWebhookSubscriptions: [WebhookSubscription]! @hasOrganizationRole(role: ["ADMIN"]) @isVerified @acceptTermsAndConditions @isAuthenticated
  getAvailableWebhooks: [Webhook!]! @hasOrganizationRole(role: ["ADMIN"]) @isVerified @acceptTermsAndConditions @isAuthenticated
  getAllWebhookExecutions(offset: Int!, limit: Int!): PaginatedWebhookExecution! @hasOrganizationRole(role: ["ADMIN"]) @isVerified @acceptTermsAndConditions @isAuthenticated
}

extend type Mutation {
  subscribe(input: SubcribeWebhookInput!): Boolean! @hasOrganizationRole(role: ["ADMIN"]) @isVerified @acceptTermsAndConditions @isAuthenticated
  updateSubscription(input: UpdateSubscriptionInput!): Boolean! @hasOrganizationRole(role: ["ADMIN"]) @isVerified @acceptTermsAndConditions @isAuthenticated
  triggerManualSend(input: TriggerManualSendInput!): TriggerManualSendResponse
}

type WebhookSubscription {
  id: String
  type: Hooks!,
  created: String!,
  apiKey: String
  organizationId: String!
  description: String,
  enabledTopics: [String]!
  status: HookSubscriptionStatus!,
  url: String!
}

type WebhookTopic {
  name: String!
  description: String!
}

type Webhook {
  name: String!
  type: Hooks!
  topics: [WebhookTopic!]!
}

enum Hooks {
  orders
}

enum HookSubscriptionStatus {
  enabled,
  disabled
}

input SubcribeWebhookInput {
  url: String!
  topics: [String!]!
  apiKey: String
  description: String
}

input UpdateSubscriptionInput {
  id: String!
  url: String!
  apiKey: String
  organizationId: String!
  enabledTopics: [String!]!
  status:  HookSubscriptionStatus!
  description: String
}

type WebhookExecution {
  id: String!
  webhook: WebhookSubscription!
  payload: BaseWebhookPayload!
  nextExecutionAt: String
  executed: Boolean
}

type BaseWebhookPayload {
  event: String!
}

type PaginatedWebhookExecution {
  data: [WebhookExecution]!
  count: Int!
}

type TriggerManualSendResponse {
  success: Boolean!
  nextExecution: String
}

input TriggerManualSendInput {
  executionId: String!
}