extend type Mutation{
  signUp(input: SignUpInput!): User!
  userVerifyEmail(input: UserVerifyEmailInput!): Boolean
  userRecoveryPassword(input: UserRecoveryPasswordInput!): Boolean
  userPasswordChange(input: UserPasswordChangeInput!): Boolean
}

input UserPasswordChangeInput{
  hash: String!
  password: String!
}

input UserRecoveryPasswordInput{
  email: String!
}

input UserVerifyEmailInput{
  verificationHash: String!
}

input SignUpInput{
  username: String!
  email: String!
  password: String!
}

type User{
  id: String!
  username: String!
  email: String!
}