---
apiVersion: v1
kind: Service
metadata:
  name: plugone-api
  labels:
    app: plugone-api
    service: plugone-api
spec:
  type: ClusterIP
  ports:
    - name: "web"
      port: 80
      targetPort: "web"
  selector:
    app: plugone-api
