extend type Mutation {
  handleCart(input: HandleCartInput): Boolean!
}

input AbandonedCartItem {
  productId: String!
  imageUrl: String!
  name: String!
  quantity: Int!
}

input AbandonedCartClientProfileData {
  email: String!
  phone: String
}

input HandleCartInput {
  organizationId: String!
  orderFormId: String!
  provider: String!
  clientProfileData: AbandonedCartClientProfileData!
  items: [AbandonedCartItem]!
}
