extend type Query{
    menuTree: [MenuTree]! @hasServiceRole(role: ["ADMIN","RESPONSIBLE","ANALYST"]) @isVerified @isAuthenticated 
}

type MenuTree{
    name: String!
    slug: String
    children: [MenuChildren]
}

type MenuChildren{
    name: String
    slug: String
    children: [SubMenuChildren]
}

type SubMenuChildren{
    slug: String
    name: String
}



