extend type Query{
  verifyOrganizationName(input: VerifyOrganizationNameInput!): Boolean @isAuthenticated
  listMyOrganizations: [Organization]! @isVerified @isAuthenticated
  organizationDetails(input: OrganizationDetailsInput!): Organization! @hasOrganizationRole(role: ["ADMIN", "MEMBER"]) @isVerified @isAuthenticated
  listUsersInOrganization(input: ListUsersInOrganizationInput!): ListUsersInOrganizationPayload! @hasOrganizationRole(role: ["ADMIN", "MEMBER"]) @isVerified @isAuthenticated
  findUsersToOrganization(input: FindUsersToOrganizationInput!): [FindUsersToOrganizationPayload]! @hasOrganizationRole(role: ["ADMIN"]) @isVerified @isAuthenticated
}

type ListUsersInOrganizationPayload{
  count: Int!
  usersOrganizations: [UserOrganization]!
}

input OrganizationDetailsInput{
  organizationName: String!
}

input ListUsersInOrganizationInput{
  name: String
  organizationId: String!
  offset: Int
  limit: Int
  showActive: Boolean
}

input FindUsersToOrganizationInput{
  name: String!
  organizationId: String!
}

type FindUsersToOrganizationPayload{
  user: User!
  inviteStatus: OrganizationInviteStatus
}

input VerifyOrganizationNameInput{
  name: String!
}

extend type Mutation{
  createOrganization(input: CreateOrganizationInput!): Organization! @isVerified @isAuthenticated 
  setCurrentOrganization(input: SetCurrentOrganizationInput!): Boolean! @isVerified @isAuthenticated 
  organizationUploadImage(input: OrganizationUploadImageInput!): Organization! @hasOrganizationRole(role: ["ADMIN"]) @isVerified @isAuthenticated 
  inviteUserToOrganization(input: InviteUserToOrganizationInput!): Boolean! @hasOrganizationRole(role: ["ADMIN"]) @isVerified @isAuthenticated
  responseOrganizationInvite(input: ResponseOrganizationInviteInput!): ResponseOrganizationInvitePayload!
  inativeUsersInOrganization(input: InativeUsersInOrganizationInput!): [InativeUsersInOrganizationPayload]! @hasOrganizationRole(role: ["ADMIN"]) @isVerified @isAuthenticated
  handleUserPermissionInOrganization(input: HandleUserPermissionInOrganizationInput!): UserOrganizationRole! @hasOrganizationRole(role: ["ADMIN"]) @isVerified @isAuthenticated
}

input SetCurrentOrganizationInput{
  organizationId: String!
}

type InativeUsersInOrganizationPayload{
  userOrganization: UserOrganization
  userError: UserError
}

type UserError{
  message: String!
  userId: String!
}

input OrganizationUploadImageInput{
  mimetype: String
  data: Upload!
  organizationId: String!
}

type ResponseOrganizationInvitePayload{
  status: Boolean!
  email: String
}

input HandleUserPermissionInOrganizationInput{
  userId: String!
  organizationId: String!
  permission: OrganizationRoleName!
}

input InativeUsersInOrganizationInput{
  usersId: [String]!
  organizationId: String!
}

input ResponseOrganizationInviteInput{
  inviteHash: String!
  response: OrganizationInviteStatus!
}

enum OrganizationInviteStatus {
    refused,
    pendent,
    accept,
    exited
}

input InviteUserToOrganizationInput {
  organizationId: String!
  users: [InviteUsersInput]!
}

input InviteUsersInput {
  id: String
  email: String!
  role: OrganizationRoleName
}

input CreateOrganizationInput{
  name: String!
  contactEmail: String!
}

type Organization{
  name: String!
  contactEmail: String!
  id: String!
  active: Boolean!
  user: User! @isVerified @isAuthenticated # TODO somente admin pode ver o founder
  updatedAt: Datetime!
  createdAt: Datetime!
  logo: String
  hasMember: Boolean!
  organizationRole: [OrganizationRole]!
  services: [Service]!
}

type UserOrganizationRole{
  id: String!
  userOrganization: UserOrganization!
  organizationRole: OrganizationRole!
  createdAt: Datetime!
  updatedAt: Datetime!
}

type UserOrganization{
  id: String!
  inviteStatus: OrganizationInviteStatus!
  inviteHash: String
  updatedAt: Datetime!
  createdAt: Datetime!
  organization: Organization!
  user: User!
  active: Boolean!
  organizationRole: OrganizationRole!
}

type OrganizationRole{
    id: String!
    name: OrganizationRoleName!
    createdAt: Datetime!
    updatedAt: Datetime!
}

enum OrganizationRoleName {
    ADMIN,
    MEMBER
}