extend type Mutation{
    affiliateGenerateShortenerUrl(input: AffiliateGenerateShortenerUrlInput!): UserOrganizationServiceRolesUrlShortener! @hasServiceRole(role: ["ANALYST"]) @isVerified @isAuthenticated 
    generateSalesJwt(input: GenerateSalesJwtInput!): String!
    createAffiliateBankValues(input: CreateAffiliateBankValuesInput!): UserOrganizationService! @hasServiceRole(role: ["ANALYST"]) @isVerified @isAuthenticated
}

input GenerateSalesJwtInput{
    email: String!
    organizationId: String!
    serviceName: ServiceName!
}

extend type Query{
    listAffiliateShorterUrl(input: ListAffiliateShorterUrlInput!): [UserOrganizationServiceRolesUrlShortener]! @hasServiceRole(role: ["ANALYST"]) @isVerified @isAuthenticated 
}

input CreateAffiliateBankValuesInput{
  name: String!
  agency: String!
  account: String!
  accountDigit: String!
  document: String!
  brazilBankId: String!
  serviceName: ServiceName!
}

input ListAffiliateShorterUrlInput{
    userOrganizationServiceId: String!
    serviceName: ServiceName!
}

input AffiliateGenerateShortenerUrlInput{
    originalUrl: String!
    serviceName: ServiceName!
}

type UserOrganizationServiceRolesUrlShortener {
    id: String!
    shortenerUrl: ShortenerUrl!
    userOrganizationService: UserOrganizationService!
    createdAt: Datetime!
    updatedAt: Datetime!
}